application: rgb-boxes
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /
  static_files: index.html
  upload: index\.html

- url: /styles
  static_dir: styles

- url: /scripts
  static_dir: scripts

- url: /images
  static_dir: images

- url: /images/(.*)
  static_files: images/\1
  upload: images/(.*)

libraries:
- name: webapp2
  version: "2.5.2"
